import React, { useState, useEffect } from 'react'
import { useAuth } from '../contexts/AuthContext'
import { usersAPI, reportsAPI } from '../services/api'
import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'

const TeamManagement = () => {
  const { user } = useAuth()
  const [loading, setLoading] = useState(true)
  const [teamMembers, setTeamMembers] = useState([])
  const [selectedPeriod, setSelectedPeriod] = useState('month')
  const [filter, setFilter] = useState('all')
  const [performanceData, setPerformanceData] = useState([])
  const [error, setError] = useState('')
  const [successMessage, setSuccessMessage] = useState('')

  // ... rest of your existing state and useEffect ...

  // EXPORT FUNCTIONS - ADD THESE BACK:

  // Export Team Performance to PDF
  const exportToPDF = () => {
    try {
      const doc = new jsPDF()
      
      // Title
      doc.setFontSize(20)
      doc.text('Team Performance Report', 20, 20)
      
      // Subtitle
      doc.setFontSize(12)
      doc.text(`Period: ${selectedPeriod.charAt(0).toUpperCase() + selectedPeriod.slice(1)}`, 20, 30)
      doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 37)
      doc.text(`Generated by: ${user?.name || 'Supervisor'}`, 20, 44)

      // Check if we have performance data
      if (performanceData.length === 0) {
        doc.text('No performance data available', 20, 60)
      } else {
        // Performance Summary Table
        const tableData = performanceData.map((data, index) => {
          const member = teamMembers.find(m => m._id === data.memberId || m.id === data.memberId)
          return [
            index + 1,
            member?.name || 'Unknown',
            member?.region || 'N/A',
            data.stats?.totalReports || 0,
            data.stats?.totalDoctors || 0,
            data.stats?.totalOrders || 0,
            `RWF ${(data.stats?.totalValue || 0).toLocaleString()}`,
            data.lastActivity || 'No activity'
          ]
        })

        autoTable(doc, {
          head: [['#', 'Name', 'Region', 'Reports', 'Doctors', 'Orders', 'Value', 'Last Activity']],
          body: tableData,
          startY: 50,
          theme: 'grid',
          headStyles: { fillColor: [59, 130, 246] },
          styles: { fontSize: 10, cellPadding: 3 },
          columnStyles: {
            0: { cellWidth: 10 },
            1: { cellWidth: 40 },
            2: { cellWidth: 30 },
            6: { cellWidth: 35 }
          }
        })

        // Add totals
        const totals = getTotals()
        const finalY = doc.lastAutoTable?.finalY || 70
        doc.setFontSize(11)
        doc.setFont(undefined, 'bold')
        doc.text('Team Totals:', 20, finalY + 10)
        doc.setFont(undefined, 'normal')
        doc.text(`Total Reports: ${totals.reports}`, 20, finalY + 18)
        doc.text(`Total Doctors Visited: ${totals.doctors}`, 20, finalY + 26)
        doc.text(`Total Orders: ${totals.orders}`, 20, finalY + 34)
        doc.text(`Total Value: RWF ${totals.value.toLocaleString()}`, 20, finalY + 42)
      }

      // Save PDF
      doc.save(`Team-Performance-${selectedPeriod}-${new Date().toISOString().split('T')[0]}.pdf`)
      
      setSuccessMessage('PDF exported successfully!')
    } catch (error) {
      console.error('Error exporting PDF:', error)
      setError('Failed to export PDF. Please try again.')
    }
  }

  // Export individual member PDF
  const exportMemberPDF = (member, performance) => {
    try {
      if (!performance) {
        setError('No performance data available for this member')
        return
      }

      const doc = new jsPDF()
      
      // Title
      doc.setFontSize(20)
      doc.text(`${member.name} - Performance Report`, 20, 20)
      
      // Subtitle
      doc.setFontSize(12)
      doc.text(`Period: ${selectedPeriod.charAt(0).toUpperCase() + selectedPeriod.slice(1)}`, 20, 30)
      doc.text(`Region: ${member.region || 'N/A'}`, 20, 37)
      doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 44)

      // Summary stats
      doc.setFontSize(14)
      doc.text('Performance Summary', 20, 60)
      
      const summaryData = [
        ['Total Reports', performance.stats?.totalReports || 0],
        ['Total Doctors Visited', performance.stats?.totalDoctors || 0],
        ['Total Pharmacies Visited', performance.stats?.totalPharmacies || 0],
        ['Total Dispensaries Visited', performance.stats?.totalDispensaries || 0],
        ['Total Orders', performance.stats?.totalOrders || 0],
        ['Total Order Value', `RWF ${(performance.stats?.totalValue || 0).toLocaleString()}`],
        ['Average Doctors/Day', performance.stats?.avgDoctorsPerDay || 0],
        ['Average Orders/Day', performance.stats?.avgOrdersPerDay || 0],
        ['Average Value/Day', `RWF ${performance.stats?.avgValuePerDay || 0}`]
      ]

      autoTable(doc, {
        body: summaryData,
        startY: 70,
        theme: 'grid',
        styles: { fontSize: 10, cellPadding: 3 },
        columnStyles: {
          0: { fontStyle: 'bold', cellWidth: 80 },
          1: { cellWidth: 60 }
        }
      })

      // Recent Reports Table if available
      if (performance.reports && performance.reports.length > 0) {
        const recentY = doc.lastAutoTable?.finalY + 15 || 100
        doc.setFontSize(14)
        doc.text('Recent Reports', 20, recentY)

        const reportData = performance.reports.slice(0, 10).map(report => [
          new Date(report.report_date || report.date).toLocaleDateString(),
          calculateTotalDoctors(report),
          report.pharmacies || 0,
          report.dispensaries || 0,
          report.orders_count || report.orders || 0,
          `RWF ${(report.orders_value || report.value || 0).toLocaleString()}`,
          (report.summary?.substring(0, 30) || '') + (report.summary?.length > 30 ? '...' : '')
        ])

        autoTable(doc, {
          head: [['Date', 'Doctors', 'Pharmacy', 'Dispensary', 'Orders', 'Value', 'Notes']],
          body: reportData,
          startY: recentY + 5,
          theme: 'grid',
          styles: { fontSize: 8, cellPadding: 2 },
          columnStyles: {
            6: { cellWidth: 40 }
          }
        })
      }

      doc.save(`${member.name.replace(/[^a-z0-9]/gi, '_')}-Performance-${selectedPeriod}.pdf`)
      setSuccessMessage(`${member.name}'s report exported successfully!`)
    } catch (error) {
      console.error('Error exporting member PDF:', error)
      setError('Failed to export member report. Please try again.')
    }
  }

  // Helper function for calculating doctors
  const calculateTotalDoctors = (report) => {
    if (!report) return 0
    const doctors = 
      (report.dentists || 0) +
      (report.physiotherapists || 0) +
      (report.gynecologists || 0) +
      (report.internists || 0) +
      (report.general_practitioners || report.generalPractitioners || 0) +
      (report.pediatricians || 0) +
      (report.dermatologists || 0)
    
    if (doctors === 0 && report.total_doctors) {
      return report.total_doctors
    }
    
    return doctors
  }

  // ... rest of your existing functions (getTotals, addTeamMember, toggleActiveStatus, etc.) ...

  // Update the member actions to include export button
  const TeamMemberCard = ({ member, performance, rank, onToggle }) => (
    <div className="member-card">
      {/* ... existing member card content ... */}
      
      <div className="member-actions">
        <button 
          onClick={() => exportMemberPDF(member, performance)} 
          className="action-button export"
          disabled={!performance}
        >
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M21 15V19C21 19.5304 20.7893 20.0391 20.4142 20.4142C20.0391 20.7893 19.5304 21 19 21H5C4.46957 21 3.96086 20.7893 3.58579 20.4142C3.21071 20.0391 3 19.5304 3 19V15" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
            <path d="M7 10L12 15L17 10" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
            <path d="M12 15V3" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
          </svg>
          Export
        </button>
        <button onClick={onToggle} className={`action-button toggle ${
          member.is_active === false || member.status === 'inactive' ? 'activate' : 'deactivate'
        }`}>
          {member.is_active === false || member.status === 'inactive' ? 'Activate' : 'Deactivate'}
        </button>
      </div>
    </div>
  )

  // Add Export Section to your JSX return:
  return (
    <div className="team-management-container">
      {/* ... existing header ... */}
      
      {/* Add Export Button to Header Actions */}
      <div className="header-actions">
        <button onClick={refreshData} className="refresh-button">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            {/* refresh icon */}
          </svg>
          Refresh
        </button>
        <button onClick={exportToPDF} className="export-team-button">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M21 15V19C21 19.5304 20.7893 20.0391 20.4142 20.4142C20.0391 20.7893 19.5304 21 19 21H5C4.46957 21 3.96086 20.7893 3.58579 20.4142C3.21071 20.0391 3 19.5304 3 19V15" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
            <path d="M7 10L12 15L17 10" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
            <path d="M12 15V3" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
          </svg>
          Export Team Report
        </button>
      </div>
      
      {/* ... rest of your JSX ... */}
      
      {/* Export Options Card */}
      <div className="export-card">
        <div className="card-header">
          <h3>Export Reports</h3>
        </div>
        <div className="export-grid">
          <ExportButton 
            icon="📊"
            title="Export Team Report" 
            description="Generate comprehensive PDF report for the entire team"
            onClick={exportToPDF}
            color="#3b82f6"
          />
          <ExportButton 
            icon="📈"
            title="Export All Member Reports" 
            description="Export detailed reports for all team members"
            onClick={() => {
              if (performanceData.length === 0) {
                setError('No performance data available to export')
                return
              }
              // Export all members one by one
              performanceData.forEach((perf, index) => {
                const member = teamMembers.find(m => m._id === perf.memberId || m.id === perf.memberId)
                if (member && perf) {
                  setTimeout(() => exportMemberPDF(member, perf), index * 1000)
                }
              })
              setSuccessMessage('Exporting all member reports...')
            }}
            color="#10b981"
          />
          <ExportButton 
            icon="🌍"
            title="Export by Region" 
            description="Generate regional performance reports"
            onClick={() => {
              // Group by region and export
              const regions = {}
              teamMembers.forEach(member => {
                const region = member.region || 'Unknown'
                if (!regions[region]) regions[region] = []
                regions[region].push(member)
              })
              
              Object.keys(regions).forEach((region, index) => {
                setTimeout(() => {
                  const doc = new jsPDF()
                  doc.text(`${region} - Team Report`, 20, 20)
                  // Add region-specific content
                  doc.save(`${region}-Report.pdf`)
                }, index * 1000)
              })
              setSuccessMessage('Exporting regional reports...')
            }}
            color="#8b5cf6"
          />
        </div>
      </div>
    </div>
  )
}

// Export Button Component
const ExportButton = ({ icon, title, description, onClick, color }) => (
  <button onClick={onClick} className="export-option" style={{ borderColor: color }}>
    <span className="export-icon" style={{ color: color }}>{icon}</span>
    <div className="export-content">
      <div className="export-title">{title}</div>
      <div className="export-description">{description}</div>
      <div className="export-cta" style={{ color: color }}>
        Click to export →
      </div>
    </div>
  </button>
)

// Add these CSS styles:
const pdfExportStyles = `
/* Export Button Styles */
.export-team-button {
  background: linear-gradient(135deg, #10b981 0%, #059669 100%);
  color: white;
  border: none;
  border-radius: 8px;
  padding: 10px 20px;
  cursor: pointer;
  font-size: 14px;
  font-weight: 500;
  display: flex;
  align-items: center;
  gap: 8px;
  transition: all 0.2s ease;
}

.export-team-button:hover {
  background: linear-gradient(135deg, #059669 0%, #047857 100%);
  transform: translateY(-1px);
  box-shadow: 0 4px 12px rgba(16, 185, 129, 0.3);
}

/* Export Card */
.export-card {
  background: white;
  padding: 32px;
  border-radius: 16px;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.05);
  border: 1px solid #e2e8f0;
  margin-top: 30px;
}

.export-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: 20px;
}

.export-option {
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  padding: 24px;
  background: white;
  border: 2px solid;
  border-radius: 12px;
  cursor: pointer;
  transition: all 0.3s ease;
  text-align: left;
  width: 100%;
  height: 100%;
}

.export-option:hover {
  background: #f8fafc;
  transform: translateY(-3px);
  box-shadow: 0 8px 25px rgba(0, 0, 0, 0.1);
}

.export-icon {
  font-size: 32px;
  margin-bottom: 16px;
}

.export-content {
  flex: 1;
}

.export-title {
  font-weight: 600;
  color: #1e293b;
  margin-bottom: 8px;
  font-size: 18px;
}

.export-description {
  font-size: 15px;
  color: #64748b;
  line-height: 1.5;
  margin-bottom: 16px;
}

.export-cta {
  font-weight: 500;
  font-size: 14px;
  display: flex;
  align-items: center;
  gap: 8px;
}

/* Member Actions - Export Button */
.action-button.export {
  background: #3b82f6;
  color: white;
  border: none;
  border-radius: 6px;
  padding: 8px 12px;
  cursor: pointer;
  font-size: 12px;
  font-weight: 500;
  display: flex;
  align-items: center;
  gap: 6px;
  transition: all 0.2s ease;
  flex: 1;
}

.action-button.export:hover:not(:disabled) {
  background: #2563eb;
  transform: translateY(-1px);
}

.action-button.export:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.action-button.export svg {
  width: 14px;
  height: 14px;
}
`

// Add styles to document
if (typeof document !== 'undefined') {
  const styleSheet = document.createElement('style')
  styleSheet.textContent = pdfExportStyles
  document.head.appendChild(styleSheet)
}

export default TeamManagement
